### PR TITLE
little fix

### PR DESCRIPTION
**Pull request by wpt**

### CODE REVIEW

**Comment by rnicholus** [comment]
Thanks a lot for catching this and taking the time to open up a pull request with the fix!

**Comment by foolip** [comment]
@rnicholus, this is a long shot, but I'm wondering if by any chance you know how to get in touch with @wpt? See https://github.com/wpt/myvimrc/issues/1 :)

**Comment by rnicholus** [comment]
Sorry, I do not, and don’t recall interacting with this contributor outside of this PR. Perhaps he will respond here. Best of luck.

**Comment by foolip** [comment]
OK, thanks!

**Pull request merged**
